### ISSUE TITLE
BUG: file not found

### ISSUE THREAD

**Issue by GFdevelop** [droserasprout/pacman-fix-permissions#1]
```
(100/912) dislocker 0.7.1-2
=> dislocker package is missing, downloading
Traceback (most recent call last):
  File "/usr/bin/pacman-fix-permissions", line 79, in <module>
    main()
  File "/usr/bin/pacman-fix-permissions", line 57, in main
    old_mode = int(lstat(p).st_mode & 0o7777)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dislocker'
```

**Comment by droserasprout** [comment]
Hello and thanks for reporting. This script doesn't check file permissions of packages from AUR. Maybe I'll add this feature as non-default unsafe option. I can't find dislocker in Arch repos. From where did you get it? Also dislocker 0.7.1-2 package from AUR actually doesn't include /usr/share/dislocker path:
`➜  ~ pacman -Q dislocker 
dislocker 0.7.1-2
➜  ~ pacman -Ql dislocker
dislocker /usr/
dislocker /usr/bin/
dislocker /usr/bin/dislocker
dislocker /usr/bin/dislocker-bek
dislocker /usr/bin/dislocker-file
dislocker /usr/bin/dislocker-find
dislocker /usr/bin/dislocker-fuse
dislocker /usr/bin/dislocker-metadata
dislocker /usr/lib/
dislocker /usr/lib/libdislocker.so
dislocker /usr/lib/libdislocker.so.0.7
dislocker /usr/lib/libdislocker.so.0.7.1
dislocker /usr/share/
dislocker /usr/share/doc/
dislocker /usr/share/doc/dislocker/
dislocker /usr/share/doc/dislocker/CHANGELOG
dislocker /usr/share/doc/dislocker/README
dislocker /usr/share/licenses/
dislocker /usr/share/licenses/dislocker/
dislocker /usr/share/licenses/dislocker/LICENSE
dislocker /usr/share/man/
dislocker /usr/share/man/man1/
dislocker /usr/share/man/man1/dislocker-file.1.gz
dislocker /usr/share/man/man1/dislocker-find.1.gz
dislocker /usr/share/man/man1/dislocker-fuse.1.gz
dislocker /usr/share/man/man1/dislocker.1.gz
`

**Comment by GFdevelop** [comment]
```
> pacman -Q dislocker
dislocker 0.7.1-2
> pacman -Ql dislocker
dislocker /usr/
dislocker /usr/bin/
dislocker /usr/bin/dislocker
dislocker /usr/bin/dislocker-bek
dislocker /usr/bin/dislocker-file
dislocker /usr/bin/dislocker-find
dislocker /usr/bin/dislocker-fuse
dislocker /usr/bin/dislocker-metadata
dislocker /usr/lib/
dislocker /usr/lib/libdislocker.so
dislocker /usr/lib/libdislocker.so.0.7
dislocker /usr/lib/libdislocker.so.0.7.1
dislocker /usr/share/
dislocker /usr/share/doc/
dislocker /usr/share/doc/dislocker/
dislocker /usr/share/doc/dislocker/CHANGELOG
dislocker /usr/share/doc/dislocker/README
dislocker /usr/share/licenses/
dislocker /usr/share/licenses/dislocker/
dislocker /usr/share/licenses/dislocker/LICENSE
dislocker /usr/share/man/
dislocker /usr/share/man/man1/
dislocker /usr/share/man/man1/dislocker-file.1.gz
dislocker /usr/share/man/man1/dislocker-find.1.gz
dislocker /usr/share/man/man1/dislocker-fuse.1.gz
dislocker /usr/share/man/man1/dislocker.1.gz
```
I get it from AUR.
