### ISSUE TITLE
Tries to open wrong package file

### ISSUE THREAD

**Issue by kloetzl** [droserasprout/pacman-fix-permissions#7]
pacman-fix-permissions expects packages to be compressed by .xz whereas the default is .zst now.

**Comment by droserasprout** [comment]
Sorry, I completely forgot about this script. Gonna fix this issue in a day or two.

**Comment by raneon** [comment]
It would be nice if this could be followed up eventually.

**Comment by kloetzl** [comment]
I tried to fix it myself at some point, but to no avail. I think the problem was that python doesn't understand .zstd, yet?

**Comment by kloetzl** [comment]
Looks fixed in 1.1.1. Thanks!
